### ISSUE TITLE
Exception during configuration

### ISSUE THREAD

**Issue by PavelAltynnikov** [architecture-building-systems/revitpythonshell#118]
Hi.
When I try to add properties of an external script before I click the Add button, an exception is thrown
![image](https://user-images.githubusercontent.com/45833327/146073355-b9f13c6f-49bc-467c-9fe9-e3eeff7924b4.png)
Here is part of the exception message.
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at RevitPythonShell.ConfigureCommandsForm.txtCommandPath_TextChanged(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnTextChanged(EventArgs e)
   at System.Windows.Forms.TextBoxBase.WmReflectCommand(Message& m)
   at System.Windows.Forms.TextBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
I understand that this may not be the correct logic and i must first click on the Add button, but probably an exception should not occur.

**Comment by Ianhuuuuang** [comment]
您好，邮件已收到，尽快给您回复。
