### ISSUE TITLE
Revit 2018.3 crushes when running python shell

### ISSUE THREAD

**Issue by tdafos** [architecture-building-systems/revitpythonshell#90]
Hello
I am trying to run the python shell in Revit 2018.3 I downloaded the installer for Revit 2018. I installed it, but every time I run the shell Revit crushes. I get the following error.

Application: Revit.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.MissingMethodException
Stack:
   at PythonConsoleControl.PythonTextEditor.CheckAndOutputWriteBuffer(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

Am I missing something?

**Comment by tdafos** [comment]
Solved it. I needed to install .NET 4.7. Now it works fine.
